/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vérifie que le service répond */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Service opérationnel */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liste les méthodes de vote installées avec leur manifeste */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Catalogue des modules */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            voting_methods?: components["schemas"]["ModuleManifest"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crée un compte (rôle Organizer par défaut) et ouvre une session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description Compte créé, session ouverte */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description Email invalide, mot de passe trop court, ou email déjà utilisé */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Connexion par email/mot de passe */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Session ouverte */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description Email ou mot de passe incorrect (message volontairement générique, cf. docs/SECURITY.md §7) */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ferme la session associée au jeton présenté */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Session fermée */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Jeton absent ou invalide */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Renvoie l'utilisateur associé au jeton présenté
         * @description Permet au frontend de retrouver l'utilisateur courant après un rechargement de page (le jeton survit en `localStorage`, mais l'utilisateur qu'il désigne ne peut être connu sans cette route) — cf. docs/DEVLOG.md, itération 6.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Utilisateur authentifié par le jeton présenté */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description Jeton absent ou invalide */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/g1/challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Génère un défi à signer pour la connexion par identité Ğ1v2 optionnelle
         * @description Première moitié du protocole de connexion Ğ1 (addendum v0.3, « Identité décentralisée ») — cf. docs/G1_INTEGRATION.md §4. Le défi renvoyé doit être signé localement, dans le portefeuille Ğ1 de l'utilisateur (Cesium², Ğecko...), sans que la phrase de 12 mots ne quitte jamais son appareil. Sans corps de requête. Prouve uniquement la possession de clé, PAS l'appartenance à la toile de confiance (cf. réponse 200 de /auth/g1/verify).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Défi frais, valide 5 minutes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["G1ChallengeResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/g1/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Vérifie la signature du défi et ouvre une session (identité Ğ1v2 optionnelle)
         * @description Seconde moitié du protocole. Retrouve l'utilisateur déjà lié à cette clé publique, ou en provisionne un nouveau (rôle Voter, dans `organization_id`) lors de la toute première preuve réussie pour cette clé — cf. docs/G1_INTEGRATION.md §4. Ne vérifie QUE la possession de la clé privée (signature ed25519 valide), jamais l'appartenance à la toile de confiance Ğ1 (vérification réseau non câblée dans ce déploiement, cf. crates/agoravote-g1/README.md).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["G1VerifyRequest"];
                };
            };
            responses: {
                /** @description Signature valide, session ouverte */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AuthResponse"];
                    };
                };
                /** @description Défi expiré/invalide, ou clé publique/signature mal formées */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Signature invalide pour la clé publique et le défi fournis (message volontairement générique, cf. docs/SECURITY.md §7) */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Crée une campagne (rôle Organizer/Admin requis) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateCampaignRequest"];
                };
            };
            responses: {
                /** @description Campagne créée (statut Draft) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Campaign"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["Forbidden"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaignId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consulte une campagne (public) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    campaignId: components["parameters"]["CampaignId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Campagne trouvée */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Campaign"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaignId}/form": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consulte le formulaire d'une campagne (public — nécessaire pour afficher les questions avant de voter) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    campaignId: components["parameters"]["CampaignId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Formulaire trouvé */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Form"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        /** Crée le formulaire d'une campagne (une seule fois, rôle Organizer/Admin requis) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    campaignId: components["parameters"]["CampaignId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateFormRequest"];
                };
            };
            responses: {
                /** @description Formulaire créé */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Form"];
                    };
                };
                /** @description Un formulaire existe déjà pour cette campagne */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaignId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publie une campagne (Draft → Published), rôle Organizer/Admin requis */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    campaignId: components["parameters"]["CampaignId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Campagne publiée */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Campaign"];
                    };
                };
                /** @description Transition invalide (ex. pas de formulaire) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaignId}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clôture une campagne (Published → Closed), rôle Organizer/Admin requis */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    campaignId: components["parameters"]["CampaignId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Campagne clôturée */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Campaign"];
                    };
                };
                /** @description Transition invalide */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaignId}/questions/{questionId}/ballots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Soumet un bulletin. Authentification OPTIONNELLE : sans jeton, vote anonyme (comportement historique) ; avec un jeton valide, le vote est nominatif et un second vote sur la même question est refusé. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    campaignId: components["parameters"]["CampaignId"];
                    questionId: components["parameters"]["QuestionId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CastBallotRequest"];
                };
            };
            responses: {
                /** @description Bulletin enregistré */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ballot"];
                    };
                };
                /** @description Campagne fermée, ou double vote d'un participant identifié */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaignId}/questions/{questionId}/tally": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lance un dépouillement avec la méthode de vote indiquée, rôle Organizer/Admin requis */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    campaignId: components["parameters"]["CampaignId"];
                    questionId: components["parameters"]["QuestionId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TallyRequest"];
                };
            };
            responses: {
                /** @description Résultat calculé et enregistré */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ResultSet"];
                    };
                };
                /** @description Méthode de vote inconnue ou aucun bulletin à dépouiller */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaignId}/questions/{questionId}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consulte le dernier résultat calculé pour cette question (public) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    campaignId: components["parameters"]["CampaignId"];
                    questionId: components["parameters"]["QuestionId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Résultat trouvé */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ResultSet"];
                    };
                };
                /** @description Aucun résultat calculé pour cette question */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaignId}/questions/{questionId}/responses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Réponses brutes pour les types de question qu'aucune méthode de vote ne dépouille (Texte, Nombre, Échelle, Classement) — public, toujours "en direct" (pas d'étape /tally). Pour Choix unique/Choix multiple, utiliser /tally puis /results à la place. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    campaignId: components["parameters"]["CampaignId"];
                    questionId: components["parameters"]["QuestionId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Réponses (et résumé statistique pour Nombre/Échelle) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QuestionResponses"];
                    };
                };
                /** @description Question à choix (utiliser /tally + /results à la place) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaignId}/questions/{questionId}/ballot_count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compte BRUT de bulletins reçus pour une question, sans dépouillement (public) — ni un résultat calculé, ni des réponses individuelles, juste leur nombre. Utilisé par la page d'invitation publique pour une participation "en direct" avant tout dépouillement. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    campaignId: components["parameters"]["CampaignId"];
                    questionId: components["parameters"]["QuestionId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Nombre de bulletins */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BallotCountResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            error: string;
        };
        ModuleManifest: {
            /** @example voting.majority */
            id: string;
            /** @example 1.0.0 */
            version: string;
            /** @example voting_method */
            kind: string;
            inputs: string[];
            parameters: string[];
            outputs: string[];
            compatible_visualizations: string[];
        };
        RegisterRequest: {
            /** Format: uuid */
            organization_id: string;
            /** Format: email */
            email: string;
            password: string;
            display_name: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        AuthResponse: {
            /** @description Jeton de session en clair — à conserver côté client, ne transite plus après cette réponse */
            token: string;
            user: components["schemas"]["User"];
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organization_id: string;
            display_name: string;
            preferred_language?: string | null;
            roles: ("Admin" | "Organizer" | "Voter" | "Auditor")[];
        };
        G1ChallengeResponse: {
            /** @description Texte exact à signer dans le portefeuille Ğ1 — à renvoyer tel quel à /auth/g1/verify */
            message: string;
            /** Format: date-time */
            expires_at: string;
        };
        G1VerifyRequest: {
            /**
             * Format: uuid
             * @description Organisation du nouvel utilisateur si cette clé publique n'est pas encore liée à un compte ; ignoré sinon
             */
            organization_id: string;
            /** @description Clé publique ed25519, 32 octets encodés en hexadécimal (avec ou sans préfixe 0x) */
            public_key_hex: string;
            /** @description Signature ed25519 de `message`, 64 octets encodés en hexadécimal */
            signature_hex: string;
            /** @description Exactement le `message` renvoyé par /auth/g1/challenge */
            message: string;
        };
        CreateCampaignRequest: {
            /** Format: uuid */
            organization_id: string;
            title: string;
        };
        Campaign: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organization_id: string;
            title: string;
            /** @enum {string} */
            status: "Draft" | "Published" | "Closed";
            /** Format: uuid */
            form_id?: string | null;
            voting_method_id?: string | null;
            voting_method_version?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            published_at?: string | null;
            /** Format: date-time */
            closed_at?: string | null;
        };
        QuestionOption: {
            id: string;
            /**
             * @example {
             *       "fr": "Améliorer les transports publics"
             *     }
             */
            labels: {
                [key: string]: string;
            };
        };
        CreateQuestionRequest: {
            /**
             * @description Intitulé traduit, par code langue (§1.1 multilinguisme natif) — même forme que QuestionOption.labels. "fr" est requis (refusé avec 400 sinon), les autres langues sont optionnelles.
             * @example {
             *       "fr": "Quelle est votre couleur préférée ?",
             *       "en": "What is your favorite color?"
             *     }
             */
            prompt: {
                [key: string]: string;
            };
            /** @enum {string} */
            type: "single_choice" | "multiple_choice" | "text" | "number" | "scale" | "ranking" | "majority_judgment";
            /** @default false */
            required: boolean;
            options?: components["schemas"]["QuestionOption"][];
            max_selections?: number | null;
            max_length?: number | null;
            min?: number | null;
            max?: number | null;
        };
        CreateFormRequest: {
            questions: components["schemas"]["CreateQuestionRequest"][];
        };
        QuestionTypeSingleChoice: {
            /** @enum {string} */
            type: "single_choice";
            options: components["schemas"]["QuestionOption"][];
        };
        QuestionTypeMultipleChoice: {
            /** @enum {string} */
            type: "multiple_choice";
            options: components["schemas"]["QuestionOption"][];
            max_selections?: number | null;
        };
        QuestionTypeText: {
            /** @enum {string} */
            type: "text";
            max_length?: number | null;
        };
        QuestionTypeNumber: {
            /** @enum {string} */
            type: "number";
            min?: number | null;
            max?: number | null;
        };
        QuestionTypeScale: {
            /** @enum {string} */
            type: "scale";
            min: number;
            max: number;
        };
        QuestionTypeRanking: {
            /** @enum {string} */
            type: "ranking";
            options: components["schemas"]["QuestionOption"][];
        };
        /** @description Jugement majoritaire (§6.2, §15.1) : chaque option reçoit une mention entière de 1 (Très défavorable) à 6 (Ne sait pas) — cf. CastBallotRequest.scores et voting.majority_judgment. */
        QuestionTypeMajorityJudgment: {
            /** @enum {string} */
            type: "majority_judgment";
            options: components["schemas"]["QuestionOption"][];
        };
        QuestionType: components["schemas"]["QuestionTypeSingleChoice"] | components["schemas"]["QuestionTypeMultipleChoice"] | components["schemas"]["QuestionTypeText"] | components["schemas"]["QuestionTypeNumber"] | components["schemas"]["QuestionTypeScale"] | components["schemas"]["QuestionTypeRanking"] | components["schemas"]["QuestionTypeMajorityJudgment"];
        Question: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            form_id: string;
            prompt: {
                [key: string]: string;
            };
            question_type: components["schemas"]["QuestionType"];
            required: boolean;
            position: number;
        };
        Form: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            campaign_id: string;
            questions: components["schemas"]["Question"][];
        };
        CastBallotRequest: {
            /**
             * Format: uuid
             * @description Ignoré si un jeton d'authentification valide est fourni (l'identité du jeton prévaut toujours)
             */
            voter_id?: string | null;
            /** @description Choix unique/multiple (id de la ou des options) ou Classement (ids de toutes les options, dans l'ordre de préférence) */
            selections?: string[];
            /** @description Jugement majoritaire : une mention entière 1 (Très défavorable) à 6 (Ne sait pas) par option, requise pour CHAQUE option de la question — cf. voting.majority_judgment */
            scores?: {
                [key: string]: number;
            } | null;
            /** @description Nombre ou Échelle */
            numeric_value?: number | null;
            /** @description Texte libre */
            text_value?: string | null;
        };
        /** @description Réponses brutes (et résumé statistique pour Nombre/Échelle) pour les types de question qu'aucune méthode de vote ne dépouille — cf. GET /campaigns/{campaignId}/questions/{questionId}/responses. */
        QuestionResponses: {
            /** @enum {string} */
            kind: "text";
            values: string[];
        } | {
            /** @enum {string} */
            kind: "numeric";
            values: number[];
            summary?: components["schemas"]["NumericSummary"];
        } | {
            /** @enum {string} */
            kind: "ranking";
            rankings: string[][];
        };
        BallotCountResponse: {
            count: number;
        };
        NumericSummary: {
            count: number;
            mean?: number | null;
            median?: number | null;
            std_dev?: number | null;
            min?: number | null;
            max?: number | null;
        };
        Ballot: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            campaign_id: string;
            /** Format: uuid */
            question_id: string;
            /** Format: uuid */
            voter_id?: string | null;
            selections: string[];
            scores?: {
                [key: string]: number;
            } | null;
            numeric_value?: number | null;
            text_value?: string | null;
            /** Format: date-time */
            cast_at: string;
        };
        TallyRequest: {
            /** @example voting.majority */
            voting_method_id: string;
            eligible_voters?: number | null;
            /** @description Fraction 0.0–1.0 */
            quorum?: number | null;
            /** @default 1 */
            seats: number;
        };
        TallyOutcome: {
            total_ballots: number;
            valid_ballots: number;
            winners: string[];
            percentages: {
                [key: string]: number;
            };
            counts: {
                [key: string]: number;
            };
            quorum_met?: boolean | null;
            metadata: {
                [key: string]: unknown;
            };
        };
        ResultSet: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            campaign_id: string;
            /** Format: uuid */
            question_id: string;
            voting_method_id: string;
            voting_method_version: string;
            outcome: components["schemas"]["TallyOutcome"];
            /** Format: date-time */
            computed_at: string;
        };
    };
    responses: {
        /** @description Jeton absent, invalide ou expiré */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authentifié mais rôle insuffisant (Organizer/Admin requis) */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Ressource introuvable */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        CampaignId: string;
        QuestionId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
